#!/bin/bash

#
# Author: Kurt L Vanderwater
# Date:   October 2, 2001
# Purpose:
#	This program is used to backup all "user" directories
#
# Updates:
#	Jan 14, 2002 - klv - Added logic for removing runtime from age equation
#	Dec 29, 2001 - klv - Changed from single file megabackup to directory based archives
#	Dec 29, 2001 - klv - commented out deletion of tempory executable
#	Dec 29, 2001 - klv - moved all variables to top of program for easy maint
#

yesterday=`date --date="yesterday" +"%Y-%m-%d"`
backup_eldest=`date --date="-1 days" +%Y%b%d`
mysql_eldest=`date --date="-5 days" +"%Y-%m-%d"`
DIRNAME=`date +%Y%b%d`		# datestamp name for directory
TMPFILE1="/tmp/backup_1"	# temporary file used to build the backup script
TMPAWK1="/tmp/backup_awk_1"	# temporary file used to define the AWK program to build the backup script
BDIR="/var/spool/backup/daily"	# base directory for the destination of all the backups.
#
# The 3 lists below are NameLIST, DirectoryLIST, & ExcludeLIST. These are used to define the name of 
# the backup file, the base directory for the backup file, and any exclusions that should occur from that
# directory structure.
#
# echo "Defining directories to process"
i=0
NLIST[$i]="bak_etc";		DLIST[$i]="/etc";	ELIST[$((i++))]="";
NLIST[$i]="bak_var";		DLIST[$i]="/var";	ELIST[$((i++))]="spool/backup --exclude=spool/mysqldumps --exclude=cache --exclude=log --exclude=tmp --exclude=www --exclude=www2 --exclude=run --exclude=lock";
NLIST[$i]="bak_usr";		DLIST[$i]="/usr";	ELIST[$((i++))]="";
NLIST[$i]="bak_root";		DLIST[$i]="/root";	ELIST[$((i++))]="";

# echo "Defining scriptbypasswd"
function scriptbypasswd() {
	# build the script to actually do the backups

	cat <<"EOF" | sed -e "s~Z-0-Z~$DIRNAME~" | sed -e "s~Z-1-Z~$BDIR~" > $TMPAWK1
	BEGIN { 
		FS = ":"
	}
	{
		if($3 >= 500 && $3 < 65000){
			if($1 == "webtrends"){
				;
			} else {
				print "cd "$6
				print "rc=$?"
				print "if (($rc == 0)); then"
				print " tar -czf Z-1-Z/Z-0-Z/"$1".tar.gz *"
				print " chmod 660 Z-1-Z/Z-0-Z/"$1".tar.gz"
				print " if [ '"$7"' = '/bin/true' ]; then"
				print "  chown "$1" Z-1-Z/Z-0-Z/"$1".tar.gz"
				print "  chgrp webadmin Z-1-Z/Z-0-Z/"$1".tar.gz"
				print " else"
				print "  chown "$1" Z-1-Z/Z-0-Z/"$1".tar.gz"
				print " fi"
				print " rc=$?"
				print " if (($rc == 0)); then"
				print " 	rm -f "$6"/backup.tar.gz"
				print " 	ln -s Z-1-Z/Z-0-Z/"$1".tar.gz "$6"/backup.tar.gz"
				print " 	chown "$1" "$6"/backup.tar.gz"
				print " fi"
				print "fi"
			}
		}
	}
EOF

	cat /etc/passwd | awk -f $TMPAWK1 > $TMPFILE1

}

# echo "Defining scriptbyhome"
function scriptbyhome() {
	# build the script to actually do the backups

	cat <<"EOF" | sed -e "s~Z-0-Z~$DIRNAME~" | sed -e "s~Z-1-Z~$BDIR~" > $TMPAWK1
	BEGIN { 
		FS = ":"
	}
	{
		print "cd /home/"$1
		print "rc=$?"
		print "if (($rc == 0)); then"
		print " tar -czf Z-1-Z/Z-0-Z/"$1".tar.gz *"
		print " chmod 660 Z-1-Z/Z-0-Z/"$1".tar.gz"
		print " chown "$1" Z-1-Z/Z-0-Z/"$1".tar.gz"
		print " rc=$?"
		print " if (($rc == 0)); then"
		print " 	rm -f "$1"/backup.tar.gz"
		print " 	ln -s Z-1-Z/Z-0-Z/"$1".tar.gz "$1"/backup.tar.gz"
		print " 	chown "$1" "$1"/backup.tar.gz"
		print " fi"
		print "fi"
	}
EOF

	ls -al /home | grep ^d | sed '1,2d' | awk '{print $9}' | awk -f $TMPAWK1 > $TMPFILE1

}

# Check and see if the backup directory exists
# echo "Check and see if the backup directory exists"
if [ ! -d $BDIR/$DIRNAME ]; then
	mkdir -p $BDIR/$DIRNAME;
fi

# save our directory position

# echo "save our directory position"
pushd . > /dev/null 2>&1

# get rid of any old backups

# echo "get rid of any old backups"
pushd . > /dev/null 2>&1
cd $BDIR
rm -fR $backup_eldest
popd

# Set folder for current Mysql Databases
pushd /var/spool/mysqldumps
mv current $yesterday
rm -fR $mysql_eldest
popd
# Backup the Mysql Databases
mysql -Bse "show databases" | grep -v "mysql\|information_schema\|lost+found" | xargs -I{} mydump.sh {}

# backup the specified directories now

# echo "backup the specified directories now"
for (( i=0; i<$((${#DLIST[@]})); i++ )); do
	pushd . > /dev/null 2>&1
	cd ${DLIST[i]}
  if [ -n ${ELIST[i]} ]; then
    tar -czf $BDIR/$DIRNAME/${NLIST[i]}.tar.gz --exclude=${ELIST[i]} *;
  else
    tar -czf $BDIR/$DIRNAME/${NLIST[i]}.tar.gz *;
  fi
	popd
done

# do the client backups now

# echo "do the client backups now"
scriptbypasswd
pushd . > /dev/null 2>&1
. $TMPFILE1
popd

# return the directory to normal

# echo "return the directory to normal"
popd

# rm -f $TMPFILE1
